import sqlalchemy as db
from dotenv import load_dotenv
from sqlalchemy import Column, Integer, String, Float, Date, DateTime
from flask_login import UserMixin

from db_config import Base, session
from app import login_manager


@login_manager.user_loader
def load_user(users_id):
    '''Загрузка пользователя по идентификатору'''
    
    if session.get('is_admin'):
        return session.query(Admins).get(users_id)

load_dotenv()



class Users(Base):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True, nullable=False)
    tg_id = db.Column(db.Integer, unique=True)
    tg_username = db.Column(db.String(100))
    phone = db.Column(db.BigInteger, nullable=False)
    name = db.Column(db.String(100), nullable=False)
    surname = db.Column(db.String(100) )
    password = db.Column(db.String(64), nullable=False)
    active = db.Column(db.SmallInteger)
    date_start = db.Column(db.Integer)
    date_end = db.Column(db.Integer)
    a_code = db.Column(db.Text)
    wb_token = db.Column(db.Text)
    tax_rate = db.Column(db.Integer)

class Sessions(Base):
    __tablename__ = "sessions"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer)
    ip = db.Column(db.BigInteger, nullable=False)
    date_start = db.Column(db.Integer)
    date_end = db.Column(db.Integer)


class Wb_Stosks(Base):
    __tablename__ = "wb_stosks"

    id = db.Column(db.Integer, primary_key=True)
    seller_id = db.Column(db.Integer)
    date_request = db.Column(db.Integer)
    lastchangedate = db.Column(db.DateTime(timezone=False))
    warehousename = db.Column(db.String(100))
    supplierarticle = db.Column(db.String(100))
    nmid = db.Column(db.Integer, nullable=False)
    barcode = db.Column(db.String(100))
    quantity = db.Column(db.Integer)
    inwaytoclient = db.Column(db.Integer)
    inwayfromclient = db.Column(db.Integer)
    quantityfull = db.Column(db.Integer)
    category = db.Column(db.String(100))
    subject = db.Column(db.String(100))
    brand = db.Column(db.String(100))
    techsize = db.Column(db.String(100))
    price = db.Column(db.Integer)
    discount = db.Column(db.Integer)
    issupply = db.Column(db.Boolean)
    isrealization = db.Column(db.Boolean)
    sccode = db.Column(db.String(100))


class Wb_Orders(Base):
    __tablename__ = "wb_orders"

    id = db.Column(db.Integer, primary_key=True)
    seller_id = db.Column(db.Integer)
    date_request = db.Column(db.Integer)
    date = db.Column(db.DateTime(timezone=False))
    lastchangedate = db.Column(db.DateTime(timezone=False))
    supplierarticle = db.Column(db.String(100))
    techsize = db.Column(db.String(100))
    barcode = db.Column(db.String(100))
    totalprice = db.Column(db.Numeric(10, 2))
    finishedprice = db.Column(db.Numeric(10, 2))
    pricewithdisc = db.Column(db.Numeric(10, 2))
    discountpercent = db.Column(db.Integer)
    spp = db.Column(db.Integer)
    warehousename = db.Column(db.String(100))
    regionname = db.Column(db.String(100))
    incomeid = db.Column(db.BigInteger)
    odid = db.Column(db.BigInteger)
    nmid = db.Column(db.BigInteger, nullable=False)
    subject = db.Column(db.String(100))
    category = db.Column(db.String(100))
    brand = db.Column(db.String(100))
    iscancel = db.Column(db.Boolean)
    issupply = db.Column(db.Boolean)
    isrealization = db.Column(db.Boolean)
    canceldate = db.Column(db.DateTime(timezone=False))
    gnumber = db.Column(db.Numeric(25, 0))
    sticker = db.Column(db.String(100))
    oblastokrugname  = db.Column(db.String(100))
    countryname = db.Column(db.String(100))
    srid = db.Column(db.String(100))
    ordertype = db.Column(db.String(100))


class Wb_Supplies(Base):
    __tablename__ = "wb_supplies"

    id = db.Column(db.Integer, primary_key=True)
    seller_id = db.Column(db.Integer)
    date_request = db.Column(db.Integer)
    incomeid = db.Column(db.BigInteger)
    number = db.Column(db.String(100))
    date = db.Column(db.DateTime(timezone=False))
    lastchangedate = db.Column(db.DateTime(timezone=False))
    supplierarticle = db.Column(db.String(100))
    techsize = db.Column(db.String(100))
    barcode = db.Column(db.String(100))
    quantity = db.Column(db.Integer)
    totalprice = db.Column(db.Float)
    dateclose = db.Column(db.DateTime(timezone=False))
    warehousename = db.Column(db.String(100))
    nmid = db.Column(db.BigInteger, nullable=False)
    status = db.Column(db.String(100))


class Wb_Sales(Base):
    __tablename__ = "wb_sales"

    id = db.Column(db.Integer, primary_key=True)
    seller_id = db.Column(db.Integer)
    date_request = db.Column(db.Integer)
    date = db.Column(db.DateTime(timezone=False))
    lastchangedate = db.Column(db.DateTime(timezone=False))
    warehousename = db.Column(db.String(100))
    countryname = db.Column(db.String(100))
    oblastokrugname = db.Column(db.String(100))
    regionname = db.Column(db.String(100))
    supplierarticle = db.Column(db.String(100))
    nmid = db.Column(db.BigInteger, nullable=False)
    barcode = db.Column(db.String(100))
    category = db.Column(db.String(100))
    subject = db.Column(db.String(100))
    brand = db.Column(db.String(100))
    techsize = db.Column(db.String(100))
    incomeid = db.Column(db.BigInteger)
    issupply = db.Column(db.Boolean)
    isrealization = db.Column(db.Boolean)
    totalprice = db.Column(db.Float)
    discountpercent = db.Column(db.Integer)
    spp = db.Column(db.Integer)
    paymentsaleamount = db.Column(db.Float)
    forpay = db.Column(db.Float)
    finishedprice = db.Column(db.Float)
    pricewithdisc = db.Column(db.Float)
    saleid = db.Column(db.String(100))
    ordertype = db.Column(db.String(100))
    sticker = db.Column(db.String(100))
    gnumber = db.Column(db.String(100))
    #odid = db.Column(db.BigInteger)
    srid = db.Column(db.String(100))


class Wb_Report_Detail(Base):
    __tablename__ = "report_detail"

    id = db.Column(db.Integer, primary_key=True)
    seller_id = db.Column(db.Integer)
    date_request = db.Column(db.Integer)
    realizationreport_id = db.Column(db.Integer)
    date_from = db.Column(db.DateTime(timezone=True))
    date_to = db.Column(db.DateTime(timezone=True))
    create_dt = db.Column(db.DateTime(timezone=True))
    currency_name = db.Column(db.Text)
    suppliercontract_code = db.Column(db.Text)
    rrd_id = db.Column(db.Integer)
    gi_id = db.Column(db.Integer)
    subject_name = db.Column(db.Text)
    nm_id = db.Column(db.BigInteger)
    brand_name = db.Column(db.Text)
    sa_name = db.Column(db.Text)
    ts_name = db.Column(db.Text)
    barcode = db.Column(db.Text)
    doc_type_name = db.Column(db.Text)
    quantity = db.Column(db.Integer)
    retail_price = db.Column(db.Numeric(10, 2))
    retail_amount = db.Column(db.Numeric(10, 2))
    sale_percent = db.Column(db.Integer)
    commission_percent = db.Column(db.Numeric(10, 2))
    office_name = db.Column(db.Text)
    supplier_oper_name = db.Column(db.Text)
    order_dt = db.Column(db.DateTime(timezone=True))
    sale_dt = db.Column(db.DateTime(timezone=True))
    rr_dt = db.Column(db.DateTime(timezone=True))
    shk_id = db.Column(db.Integer)
    retail_price_withdisc_rub = db.Column(db.Numeric(10, 2))
    delivery_amount = db.Column(db.Integer)
    return_amount = db.Column(db.Integer)
    delivery_rub = db.Column(db.Numeric(10, 2))
    gi_box_type_name = db.Column(db.Text)
    product_discount_for_report = db.Column(db.Numeric(10, 2))
    supplier_promo = db.Column(db.Numeric(10, 2))
    rid = db.Column(db.BigInteger)
    ppvz_spp_prc = db.Column(db.Numeric(10, 2))
    ppvz_kvw_prc_base = db.Column(db.Numeric(10, 2))
    ppvz_kvw_prc = db.Column(db.Numeric(10, 2))
    sup_rating_prc_up = db.Column(db.Numeric(10, 2))
    is_kgvp_v2 = db.Column(db.Numeric(10, 2))
    ppvz_sales_commission = db.Column(db.Numeric(10, 2))
    ppvz_for_pay = db.Column(db.Numeric(10, 2))
    ppvz_reward = db.Column(db.Numeric(10, 2))
    acquiring_fee = db.Column(db.Numeric(10, 2))
    acquiring_bank = db.Column(db.Text)
    ppvz_vw = db.Column(db.Numeric(10, 2))
    ppvz_vw_nds = db.Column(db.Numeric(10, 2))
    ppvz_office_id = db.Column(db.Integer)
    ppvz_office_name = db.Column(db.Text)
    ppvz_supplier_id = db.Column(db.Integer)
    ppvz_supplier_name = db.Column(db.Text)
    ppvz_inn = db.Column(db.Text)
    declaration_number = db.Column(db.Text)
    bonus_type_name = db.Column(db.Text)
    sticker_id = db.Column(db.Text)
    site_country = db.Column(db.Text)
    penalty = db.Column(db.Numeric(10, 2))
    additional_payment = db.Column(db.Numeric(10, 2))
    rebill_logistic_cost = db.Column(db.Numeric(10, 2))
    rebill_logistic_org = db.Column(db.Text)
    kiz = db.Column(db.Text)
    srid = db.Column(db.Text)


class Delivery(Base):
    __tablename__ = 'wb_excel_data'

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer)
    doc_id = Column(String)
    unloading_time = Column(DateTime)
    doc_row_number = Column(Integer)
    deliverynumber = Column(Integer)
    item = Column(String)
    item_code = Column(Integer)
    brand = Column(String)
    supplier_article = Column(String)
    name = Column(String)
    size = Column(String)
    barcode = Column(String)
    document_type = Column(String)
    payment_reason = Column(String)
    order_date = Column(Date)
    sale_date = Column(Date)
    quantity = Column(Integer)
    retail_price = Column(Float)
    realized_price = Column(Float)
    agreed_discount_percent = Column(Float)
    promo_code_percent = Column(Float)
    final_agreed_discount_percent = Column(Float)
    retail_price_with_discount = Column(Float)
    rating_reduction_percent = Column(Float)
    promotion_reduction_percent = Column(Float)
    permanent_customer_discount_percent = Column(Float)
    base_commission_percent = Column(Float)
    final_commission_percent = Column(Float)
    commission_without_vat = Column(Float)
    sales_commission_without_vat = Column(Float)
    return_and_delivery_compensation = Column(Float)
    acquiring_compensation = Column(Float)
    acquiring_comission = Column(Float)
    wildberries_commission_without_vat = Column(Float)
    vat_from_commission = Column(Float)
    seller_payment = Column(Float)
    delivery_count = Column(Integer)
    return_count = Column(Integer)
    delivery_service = Column(Float)
    total_fines = Column(Float)
    additional_payments = Column(Float)
    logistics_fines_and_payments = Column(String)
    mp_sticker = Column(String)
    bank_name = Column(String)
    office_number = Column(Integer)
    delivery_office_name = Column(String)
    partner_inn = Column(Integer)
    partner = Column(String)
    warehouse = Column(String)
    country = Column(String)
    box_type = Column(String)
    customs_declaration_number = Column(Integer)
    marking_code = Column(String)
    shk = Column(String)
    rid = Column(String)
    srid = Column(String)
    transportation_expense_compensation = Column(Float)
    transportation_organizer = Column(String)
    storage = Column(Float)
    deductions = Column(Float)
    paid_acceptance = Column(Float)


class Admins(Base, UserMixin):
    __tablename__ = "admins"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True, nullable=False)
    name = db.Column(db.String(100), nullable=False)
    surname = db.Column(db.String(100))
    password = db.Column(db.String(64), nullable=False)
    active = db.Column(db.SmallInteger)
